apiVersion: v1
kind: Template
metadata:
  name: amun-inspection-buildconfig
  annotations:
    description: A template for BuildConfig to create build on the fly.
    openshift.io/display-name: Amun inspection BuildConfig
    version: 0.5.0
    tags: amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      A template used to create dynamic builds on user requests.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: amun-inspection-buildconfig
    app: amun
    component: amun-inspection-buildconfig

objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: "${AMUN_INSPECTION_ID}"
      labels:
        app: amun
        component: amun-inspection-buildconfig
        mark: cleanup
      annotations:
        amun_specification: ${AMUN_SPECIFICATION}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "${AMUN_INSPECTION_ID}:latest"
      source:
        dockerfile: "${AMUN_GENERATED_DOCKERFILE}"
        type: Dockerfile
      resources:
        limits:
          memory: ${AMUN_MEMORY}
          cpu: ${AMUN_CPU}
        requests:
          memory: ${AMUN_MEMORY}
          cpu: ${AMUN_CPU}
      strategy:
        type: Docker
        dockerStrategy:
          env:
            - name: LANG
              value: "en_US.UTF-8"
            - name: HOME
              value: "/home/amun/"
            - name: PIPENV_CACHE_DIR
              value: "/home/amun/.cache"
            - name: PIPENV_COLORBLIND
              value: "1"
            - name: PIPENV_HIDE_EMOJIS
              value: "1"
            - name: PIPENV_NOSPIN
              value: "1"
            - name: PIPENV_VERBOSITY
              value: "1"
      triggers:
        - type: ConfigChange

parameters:
  - name: AMUN_INSPECTION_ID
    description: Id of inspection that is run.
    displayName: Inspection id
    required: true

  - description: The content of Dockerfile to be built.
    displayName: Generated Dockerfile
    required: true
    name: AMUN_GENERATED_DOCKERFILE

  - name: AMUN_CPU
    description: CPU cores requested for running job
    displayName: Job CPU
    default: 500m

  - name: AMUN_MEMORY
    description: Memory requested for running job
    displayName: Job Memory
    default: 256Mi

  - name: AMUN_SPECIFICATION
    description: Inspection specification as posted to Amun API.
    displayName: Amun specification
    required: true
